[phases]

  [phases.setup]
  nixPkgs = ["python312", "python312Packages.setuptools", "python312Packages.wheel", "gcc", "glibc"]

  [phases.build]
  cmds = [
    "python -m pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt",
    "python -c 'import redis; print(\"Redis client ready\")'",
    "python -c 'import requests; print(\"Requests ready\")'", 
    "python -c 'import flask; print(\"Flask ready\")'",
    "mkdir -p /data /app/templates /app/static"
  ]

  [phases.start]
  cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers $WORKERS --timeout 120 --keepalive 5 --log-file - --access-logfile - --error-logfile -"

[variables]
  SETUPTOOLS_USE_DISTUTILS = "stdlib"
  PYTHONPATH = "/app"
  RAILWAY_VOLUME_MOUNT_PATH = "/data"
  WORKERS = "3"
